### PR TITLE
copyData from store to store method on FS.File instance on server side

### PR DESCRIPTION
**Pull request by mxab**
see https://github.com/CollectionFS/Meteor-CollectionFS/issues/371

### CODE REVIEW

**Comment by aldeed** [comment]
@mxab, this all looks good to me, and I like it. Thanks! @raix, are you fine with merging this?

The only thought I had is that you could pretty easily accept a third argument `move`, which when `true` would additionally remove the data from the source store and clear that `copies` property. We can create a new issue for this and do it later if you don't want to add it now.

**Comment by raix** [comment]
@mxab great work!
@aldeed Lets merge, I'll do qa on cfs in the weekend - hopefully give it a nudge in two weeks time.

Btw. I agree about move

**Comment by aldeed** [comment]
@mxab, do you want to try adding `move` option now, or just merge as is?

**Comment by mxab** [comment]
I'll add the parameter

**Comment by mxab** [comment]
ok I updated the example as well

**Comment by aldeed** [comment]
@mxab, in `_copyDataFromStoreToStore`, if it's a move, it should also call `sourceStorage.adapter.remove(fileObj)` before calling the callback, and in the callback for that, if result is `false`, call the outer callback with an error. That will remove the actual data.

**Comment by mxab** [comment]
@aldeed I added the remove call if the move flag is true, but I get an error now
````
Exception while invoking method 'copy' Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.

````

I tried also adding a callback to the remove(fileObjet, function(err){...callback(..))} but I got the same error

**Comment by aldeed** [comment]
You might be able to replace `once` with `safeOnce`. If that doesn't work, then wrap the `once` callback like

```js
writeStream.once('stored', Meteor.bindEnvironment(function(result) {
  callback(null, result.fileKey);
}));
```

**Comment by mxab** [comment]
Ok I'll give it a try

**Comment by copleykj** [comment]
Hey guys, can I get a status update on this? I'be been putting off migrating a GridFS store to an S3 store for some time in the hopes of a simpler solution such as this.

**Comment by raix** [comment]
@mxab and @copleykj we are trying to get the project up in gear, we are talking about having a hangout maybe next week and we are starting a trello board to give a better overview of the project - goal is to make it easier for others to contribute - let me know if it has any interest and I'll add you guys

**Comment by aldeed** [comment]
Did I really close this? Don't think I meant to.

@mxab, were you able to make it work?

**Comment by mxab** [comment]
Yes you did :-) 
i was occupied with other stuff last few days. I will work on this this week. 
I definitely would be interested in the hangout since we already use cfs in production

**Comment by raix** [comment]
@mxab sounds cool - are you in some us timezone or EU?

**Comment by mxab** [comment]
@aldeed ok the safeOnce did the trick, also I explicitly check on false return value ```sourceStorage.adapter.remove(fileObj)===false```
the only issue that remains that it does not seem to be reactivly pushed to the frontend, the move is only visible after I reload the page

@raix "unfortunately" I'm in UTC+08:00 since a few days, but I am flexible :)

**Comment by aldeed** [comment]
@mxab, hmm, I would think your client should update reactively as long as the fileObj is reactive on the client. Do you have a shareable test proj? Is it nonreactive for both moves and copies?

**Comment by mxab** [comment]
@raix 
https://github.com/mxab/cfs-copy-data-example

it does not happen with copy neither with move

**Pull request closed without merging**
